@startuml

skinparam backgroundColor transparent
skinparam monochrome false
skinparam shadowing true




skinparam sequence {
    
    ArrowColor White
    ArrowFontColor White
    ParticipantBorderColor White


    ParticipantBorderColor White
    ParticipantBorderThickness 2
    ParticipantBackgroundColor transparent
    ParticipantFontColor White

    LifeLineBorderColor White

}

!option handwritten true

hide footbox

Alice -> Bob: test
@enduml
